sudo: required
language: python
git:
  depth: 10
  quiet: true
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      python: "3.6"
      script: ./oss_scripts/oss_lint.sh
python:
  - "2.7"
  - "3.6"
env:
  matrix:
    - TF_VERSION="tensorflow"
    - TF_VERSION="tf-nightly"
install:
  - ./oss_scripts/oss_pip_install.sh
script:
  - ./oss_scripts/oss_tests.sh
